#!/usr/bin/env node
// Convert snarkjs Groth16 (BN254/bn128) vkey+proof+public JSON into the exact
// byte serialization Soroban's BN254 host functions expect, emitted as a Rust
// fixtures module.
//   G1 (64B):  be(x) || be(y)                       (32B each, big-endian)
//   G2 (128B): be(x_c1)||be(x_c0)||be(y_c1)||be(y_c0)  (Fp2 = imaginary first!)
//   Fr (32B):  be(value)
// snarkjs stores G2 coords as [c0, c1] (real, imaginary); Soroban wants c1 then c0.
const fs = require("fs");
const path = require("path");

const dir = process.argv[2] || "circuits/build";
const out = process.argv[3] || "contracts/verifier/src/fixtures.rs";

function readJson(first, ...fallbacks) {
  for (const name of [first, ...fallbacks]) {
    const file = path.join(dir, name);
    if (fs.existsSync(file)) return JSON.parse(fs.readFileSync(file));
  }
  throw new Error(`missing ${first} in ${dir}`);
}

const base = path.basename(dir);
const vk = readJson("verification_key.json");
const proof = readJson("proof.json", `${base}_proof.json`);
const pub = readJson("public.json", `${base}_public.json`);

function be32(dec) {
  let h = BigInt(dec).toString(16);
  if (h.length > 64) throw new Error("field element exceeds 32 bytes: " + dec);
  h = h.padStart(64, "0");
  const b = [];
  for (let i = 0; i < 64; i += 2) b.push(parseInt(h.substr(i, 2), 16));
  return b;
}
const g1 = (p) => [...be32(p[0]), ...be32(p[1])];                       // 64B
const g2 = (p) => [...be32(p[0][1]), ...be32(p[0][0]),                   // x: c1,c0
                   ...be32(p[1][1]), ...be32(p[1][0])];                  // y: c1,c0
const fr = (s) => be32(s);                                              // 32B

const arr = (a) => "[" + a.join(", ") + "]";
const arrOf = (rows, n) => "[" + rows.map(arr).join(",\n    ") + "]";

const nPublic = vk.nPublic;
const icLen = vk.IC.length;          // nPublic + 1
const ic = vk.IC.map(g1);
const pubBytes = pub.map(fr);

let s = `// AUTO-GENERATED by scripts/to_soroban.js — do not edit by hand.
#![allow(clippy::all)]
#![allow(dead_code)]
pub const VK_ALPHA1: [u8; 64] = ${arr(g1(vk.vk_alpha_1))};
pub const VK_BETA2: [u8; 128] = ${arr(g2(vk.vk_beta_2))};
pub const VK_GAMMA2: [u8; 128] = ${arr(g2(vk.vk_gamma_2))};
pub const VK_DELTA2: [u8; 128] = ${arr(g2(vk.vk_delta_2))};
pub const IC: [[u8; 64]; ${icLen}] = ${arrOf(ic)};
pub const PROOF_A: [u8; 64] = ${arr(g1(proof.pi_a))};
pub const PROOF_B: [u8; 128] = ${arr(g2(proof.pi_b))};
pub const PROOF_C: [u8; 64] = ${arr(g1(proof.pi_c))};
pub const PUB: [[u8; 32]; ${nPublic}] = ${arrOf(pubBytes)};
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, s);
console.log(`wrote ${out}  (nPublic=${nPublic}, IC=${icLen})`);
